import type { Metadata, Viewport } from "next";
import "./globals.css";

// Brand fonts (Fredoka / Nunito / M PLUS Rounded 1c) load via @import in globals.css so
// the JP face ships its kana glyphs — see BRAND.md §4.

export const metadata: Metadata = {
  // `template` is used by sub-pages later (e.g. "Browse · Bayana").
  title: { default: "Bayana — JLPT vocab trainer", template: "%s · Bayana" },
  description:
    "Learn JLPT Japanese vocabulary with spaced repetition and AI-written example sentences. No setup, no ads — open it and study.",
  applicationName: "Bayana",
  // Links /manifest.webmanifest (generated by app/manifest.ts) — makes the app installable.
  manifest: "/manifest.webmanifest",
  // iOS PWA: launch chrome-free (capable). statusBarStyle "default" = a light, opaque
  // status bar with dark text — readable over our paper background. We deliberately avoid
  // "black-translucent": it would draw white status-bar text over the light UI (invisible).
  appleWebApp: { capable: true, title: "Bayana", statusBarStyle: "default" },
};

// Mobile-first viewport + theme color (SPEC §8.4; BRAND.md paper).
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#fcfaf1",
  // Extend the layout into the display's safe areas (notch / home indicator) so an
  // installed, fullscreen launch can paint edge-to-edge. Content is then padded back
  // with env(safe-area-inset-*) where it matters (see .pt-safe / .pb-safe in globals.css).
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
