// Seed example sentences for a JLPT level via the Anthropic Batch API.
//
// Usage:
//   npx tsx scripts/seed-sentences.ts [level]            # submit a batch (default N3)
//   npx tsx scripts/seed-sentences.ts --test 5 [level]   # generate N synchronously and
//                                                        # print them (prompt-quality gate)
//
// Both modes target only words that don't yet have a cached sentence, so they're
// idempotent and re-runnable. `--test` stores the (valid) sentences it generates too, so
// they aren't regenerated by the later batch.
import "dotenv/config";
import Anthropic from "@anthropic-ai/sdk";
import { db } from "@/lib/db";
import { messageParams, generateOne, upsertSentence } from "@/lib/generate";
import { Level } from "@/generated/prisma/enums";
import { costUSD } from "./cost";

function parseLevel(arg: string | undefined): Level {
  const v = (arg ?? "N3").toUpperCase();
  if (v in Level) return v as Level;
  throw new Error(`Unknown level "${arg}". Expected n5..n1.`);
}

/** Words at this level that have no ExampleSentence yet. */
function wordsNeedingSentences(level: Level, take?: number) {
  return db.word.findMany({
    where: { level, sentences: { none: {} } },
    orderBy: { id: "asc" },
    ...(take ? { take } : {}),
  });
}

async function main() {
  const argv = process.argv.slice(2);
  const level = parseLevel(argv.find((a) => /^n[1-5]$/i.test(a)));
  const client = new Anthropic(); // reads ANTHROPIC_API_KEY from the environment

  if (argv.includes("--test")) {
    const n = Number(argv[argv.indexOf("--test") + 1] ?? 5);
    const words = await wordsNeedingSentences(level, n);
    let cost = 0;
    for (const w of words) {
      const { data, usage } = await generateOne(client, w);
      cost += costUSD(usage);
      console.log(`\n${w.expression} (${w.reading}) — ${w.meaning}`);
      if (data) {
        console.log(`  JP: ${data.japanese}`);
        console.log(`  読: ${data.reading}`);
        console.log(`  EN: ${data.english}`);
        await upsertSentence(w.id, data, "ONDEMAND"); // keep valid ones (not regenerated)
      } else {
        console.log("  ⚠ malformed output — skipped");
      }
    }
    console.log(`\nTest: ${words.length} ${level} words, est. cost $${cost.toFixed(4)}.`);
    return;
  }

  // Real run: submit every remaining word at this level as one Batch request.
  const words = await wordsNeedingSentences(level);
  if (words.length === 0) {
    console.log(`No ${level} words need sentences — nothing to submit.`);
    return;
  }
  const batch = await client.messages.batches.create({
    requests: words.map((w) => ({ custom_id: w.id, params: messageParams(w) })),
  });
  console.log(`Submitted batch ${batch.id} — ${words.length} ${level} requests.`);
  console.log(`Collect results with:\n  npx tsx scripts/collect-batch.ts ${batch.id}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exitCode = 1;
  })
  .finally(() => db.$disconnect());
